//
// NftImageUploadResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct NftImageUploadResponse: Codable, JSONEncodable, Hashable {

    public var ipfsUrl: String

    public init(ipfsUrl: String) {
        self.ipfsUrl = ipfsUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case ipfsUrl = "ipfs_url"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(ipfsUrl, forKey: .ipfsUrl)
    }
}

