//
// UsersVerifyLoginRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UsersVerifyLoginRequest: Codable, JSONEncodable, Hashable {

    public var userId: String
    public var verificationCode: String

    public init(userId: String, verificationCode: String) {
        self.userId = userId
        self.verificationCode = verificationCode
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case userId = "user_id"
        case verificationCode = "verification_code"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(userId, forKey: .userId)
        try container.encode(verificationCode, forKey: .verificationCode)
    }
}

