//
// Wallet.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Wallet: Codable, JSONEncodable, Hashable {

    public var id: String
    public var createdAt: String
    public var network: Network
    public var name: String?
    public var ownerId: String?
    public var address: String

    public init(id: String, createdAt: String, network: Network, name: String? = nil, ownerId: String? = nil, address: String) {
        self.id = id
        self.createdAt = createdAt
        self.network = network
        self.name = name
        self.ownerId = ownerId
        self.address = address
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case createdAt = "created_at"
        case network
        case name
        case ownerId = "owner_id"
        case address
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(network, forKey: .network)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(ownerId, forKey: .ownerId)
        try container.encode(address, forKey: .address)
    }
}

