//
// WalletControlMode.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum WalletControlMode: String, Codable, CaseIterable {
    case developer = "developer"
    case user = "user"
}
