//
// AssetChange.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AssetChange: Codable, JSONEncodable, Hashable {

    public var token: Token?
    public var nft: Nft?
    public var amount: String
    public var rawAmount: String
    public var from: String
    public var to: String

    public init(token: Token? = nil, nft: Nft? = nil, amount: String, rawAmount: String, from: String, to: String) {
        self.token = token
        self.nft = nft
        self.amount = amount
        self.rawAmount = rawAmount
        self.from = from
        self.to = to
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case token
        case nft
        case amount
        case rawAmount = "raw_amount"
        case from
        case to
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(token, forKey: .token)
        try container.encodeIfPresent(nft, forKey: .nft)
        try container.encode(amount, forKey: .amount)
        try container.encode(rawAmount, forKey: .rawAmount)
        try container.encode(from, forKey: .from)
        try container.encode(to, forKey: .to)
    }
}

