//
// BatchTransferTokenRequestTransfersItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct BatchTransferTokenRequestTransfersItem: Codable, JSONEncodable, Hashable {

    /** recipient of the transfer */
    public var recipient: String
    /** amount to be transferred */
    public var amount: String

    public init(recipient: String, amount: String) {
        self.recipient = recipient
        self.amount = amount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case recipient
        case amount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(recipient, forKey: .recipient)
        try container.encode(amount, forKey: .amount)
    }
}

