//
// BuyGasResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct BuyGasResponse: Codable, JSONEncodable, Hashable {

    public var transactionId: String
    public var network: Network
    public var status: String

    public init(transactionId: String, network: Network, status: String) {
        self.transactionId = transactionId
        self.network = network
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case transactionId = "transaction_id"
        case network
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(transactionId, forKey: .transactionId)
        try container.encode(network, forKey: .network)
        try container.encode(status, forKey: .status)
    }
}

