//
// ContractType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum ContractType: String, Codable, CaseIterable {
    case token = "token"
    case nft = "nft"
    case other = "other"
}
