//
// GasBuyRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GasBuyRequest: Codable, JSONEncodable, Hashable {

    public var network: Network
    public var amount: String
    public var destinationAddress: String?

    public init(network: Network, amount: String, destinationAddress: String? = nil) {
        self.network = network
        self.amount = amount
        self.destinationAddress = destinationAddress
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case network
        case amount
        case destinationAddress = "destination_address"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(network, forKey: .network)
        try container.encode(amount, forKey: .amount)
        try container.encodeIfPresent(destinationAddress, forKey: .destinationAddress)
    }
}

