//
// LoginWithWalletResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct LoginWithWalletResponse: Codable, JSONEncodable, Hashable {

    public var userId: String
    public var nonce: String

    public init(userId: String, nonce: String) {
        self.userId = userId
        self.nonce = nonce
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case userId = "user_id"
        case nonce
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(userId, forKey: .userId)
        try container.encode(nonce, forKey: .nonce)
    }
}

