//
// MintNftRequestMetadata.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Metadata JSON object. */
public struct MintNftRequestMetadata: Codable, JSONEncodable, Hashable {

    /** Identifies the asset to which this NFT represents */
    public var name: String
    /** Describes the asset to which this NFT represents */
    public var description: String
    /** A URI pointing to a resource with mime type image/_* representing the asset to which this NFT represents. Consider making any images at a width between 320 and 1080 pixels and aspect ratio between 1.91:1 and 4:5 inclusive. */
    public var image: String

    public init(name: String, description: String, image: String) {
        self.name = name
        self.description = description
        self.image = image
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case description
        case image
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(description, forKey: .description)
        try container.encode(image, forKey: .image)
    }
}

