//
// ModelErrorResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ModelErrorResponse: Codable, JSONEncodable, Hashable {

    public var code: String?
    public var error: String

    public init(code: String? = nil, error: String) {
        self.code = code
        self.error = error
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case code
        case error
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(code, forKey: .code)
        try container.encode(error, forKey: .error)
    }
}

