//
// Network.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum Network: String, Codable, CaseIterable {
    case ethereum = "Ethereum"
    case polygon = "Polygon"
    case base = "Base"
    case polkadot = "Polkadot"
    case vara = "Vara"
}
