//
// NftsTransferNftRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct NftsTransferNftRequest: Codable, JSONEncodable, Hashable {

    public var network: Network
    /** from address of the transfer */
    public var from: String
    /** collection contract address */
    public var contractAddress: String
    /** recipient of the NFT transfer */
    public var recipient: String
    public var tokenId: String?
    /** On testnet, the developer_secret is always \"testnet-secret\". On mainnet, the developer_secret is set by the developer during account activation. */
    public var developerSecret: String?
    /** A 6-digit numeric pin that is only known to the user, set during wallet creation. This pin is required to sign transactions from this wallet. */
    public var userPin: String?

    public init(network: Network, from: String, contractAddress: String, recipient: String, tokenId: String? = nil, developerSecret: String? = nil, userPin: String? = nil) {
        self.network = network
        self.from = from
        self.contractAddress = contractAddress
        self.recipient = recipient
        self.tokenId = tokenId
        self.developerSecret = developerSecret
        self.userPin = userPin
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case network
        case from
        case contractAddress = "contract_address"
        case recipient
        case tokenId = "token_id"
        case developerSecret = "developer_secret"
        case userPin = "user_pin"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(network, forKey: .network)
        try container.encode(from, forKey: .from)
        try container.encode(contractAddress, forKey: .contractAddress)
        try container.encode(recipient, forKey: .recipient)
        try container.encodeIfPresent(tokenId, forKey: .tokenId)
        try container.encodeIfPresent(developerSecret, forKey: .developerSecret)
        try container.encodeIfPresent(userPin, forKey: .userPin)
    }
}

