//
// SessionChallenge.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SessionChallenge: Codable, JSONEncodable, Hashable {

    public var id: String
    public var code: String
    public var expired: Bool
    public var completed: Bool

    public init(id: String, code: String, expired: Bool, completed: Bool) {
        self.id = id
        self.code = code
        self.expired = expired
        self.completed = completed
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case code
        case expired
        case completed
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(code, forKey: .code)
        try container.encode(expired, forKey: .expired)
        try container.encode(completed, forKey: .completed)
    }
}

