//
// Simulation.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Simulation: Codable, JSONEncodable, Hashable {

    public var success: Bool
    public var assetChanges: [AssetChange]?
    public var error: String?

    public init(success: Bool, assetChanges: [AssetChange]? = nil, error: String? = nil) {
        self.success = success
        self.assetChanges = assetChanges
        self.error = error
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case success
        case assetChanges = "asset_changes"
        case error
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(success, forKey: .success)
        try container.encodeIfPresent(assetChanges, forKey: .assetChanges)
        try container.encodeIfPresent(error, forKey: .error)
    }
}

