//
// TokensBatchTransferRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TokensBatchTransferRequest: Codable, JSONEncodable, Hashable {

    public var network: Network
    /** from address of the transfer */
    public var from: String
    /** token contract address or symbol in case of the gas token to be transferred. */
    public var token: String
    /** transfers in this batch, max batch size is 50 transfers. */
    public var transfers: [BatchTransferTokenRequestTransfersItem]
    /** On testnet, the developer_secret is always \"testnet-secret\". On mainnet, the developer_secret is set by the developer during account activation. */
    public var developerSecret: String?
    /** A 6-digit numeric pin that is only known to the user, set during wallet creation. This pin is required to sign transactions from this wallet. */
    public var userPin: String?

    public init(network: Network, from: String, token: String, transfers: [BatchTransferTokenRequestTransfersItem], developerSecret: String? = nil, userPin: String? = nil) {
        self.network = network
        self.from = from
        self.token = token
        self.transfers = transfers
        self.developerSecret = developerSecret
        self.userPin = userPin
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case network
        case from
        case token
        case transfers
        case developerSecret = "developer_secret"
        case userPin = "user_pin"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(network, forKey: .network)
        try container.encode(from, forKey: .from)
        try container.encode(token, forKey: .token)
        try container.encode(transfers, forKey: .transfers)
        try container.encodeIfPresent(developerSecret, forKey: .developerSecret)
        try container.encodeIfPresent(userPin, forKey: .userPin)
    }
}

