//
// TransactionsPreviewRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TransactionsPreviewRequest: Codable, JSONEncodable, Hashable {

    public var network: Network
    /** sender of the transaction. */
    public var from: String
    public var unsignedTransaction: UnsignedTransaction

    public init(network: Network, from: String, unsignedTransaction: UnsignedTransaction) {
        self.network = network
        self.from = from
        self.unsignedTransaction = unsignedTransaction
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case network
        case from
        case unsignedTransaction = "unsigned_transaction"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(network, forKey: .network)
        try container.encode(from, forKey: .from)
        try container.encode(unsignedTransaction, forKey: .unsignedTransaction)
    }
}

