//
// UsersLoginWithWalletRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UsersLoginWithWalletRequest: Codable, JSONEncodable, Hashable {

    public var signInWallet: String

    public init(signInWallet: String) {
        self.signInWallet = signInWallet
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case signInWallet = "sign_in_wallet"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(signInWallet, forKey: .signInWallet)
    }
}

